### ISSUE TITLE
Dashboard not opening

### ISSUE THREAD

**Issue by tristanbes** [britg/New-Relic-Menus#4]
The dashboard is not opening, blank page stuck on : 

`https://login.newrelic.com/oauth_provider/authorize?response_type=code&client_id=......`

**Comment by kigster** [comment]
The reason for this is that Dashboard is linking to api.newrelic.com, while it should be linking to rpm.newrelic.com

**Comment by kigster** [comment]
Actually it should be fixed in this commit:
https://github.com/britg/New-Relic-Menus/commit/94c30afd8b6b50795fd2fe6b8e7a3947469be278

**Comment by tristanbes** [comment]
btw, can you update the version on the apple store I bought ? because the app is still not lauching itself at login and this is very annoying. (or at least sent me a precompiled .dmg so I can install the latest version available). I'm not an OS developer I don't know what to do with your repo. 

Thanks.
